name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Hugging Face Spaces
        uses: huggingface/space-ci@v1
        with:
          repo: "matthew-tendler/ai-study-summarizer"
          hf_token: ${{ secrets.HF_TOKEN }}
