name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface_hub_login:$HF_TOKEN@huggingface.co/spaces/matthew-tendler/ai-study-summarizer space-repo
          rsync -av --exclude='.git' ./ space-repo/
          cd space-repo
          git add .
          git commit -m "Update from GitHub Actions"
          git push
